import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloProvider } from "@apollo/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} px-[24px] lg:px-[156px] flex flex-col h-screen`}
      >
        <nav>
          <div className="uppercase tracking-widest mt-6 text-3xl font-bold flex justify-between mx-auto">
            <p className="text-center mx-auto md:mx-0">Rick and Morty</p>
            <span className="text-blue-900 hidden md:inline-block">
              location explorer
            </span>
          </div>
        </nav>
        <main className="py-8 flex-1">{children}</main>
        <footer className="m-auto py-4 font-boldlg:">
          Rick and Morty Location Explorer
        </footer>
      </body>
    </html>
  );
}
